### ISSUE TITLE
Declaration line euqal sign is missaligned

### ISSUE THREAD

**Issue by Obchelli** [manuelstofer/esformatter-align#4]
If I have following example
var formulaGroup = "TEST",
gridItems       = "TEST1",
itemIds         = {},
newItems        = [],
compare         = true;

ends up like this (equal sign on declaration line is 3 positions left)

var formulaGroup =  "TEST",
          gridItems        =  "TEST1",
      itemIds           = {},
      newItems       = [],
      compare        = true;

**Comment by manuelstofer** [comment]
Would you agree that it should format it like this?

``` Javascript
var formulaGroup = "TEST",
    gridItems    = "TEST1",
    itemIds      = {},
    newItems     = [],
    compare      = true;
```
