### ISSUE TITLE
Object spread alignment

### ISSUE THREAD

**Issue by andrewn** [manuelstofer/esformatter-align#5]
Opening this because I'm not sure what the behaviour should be for alignment with the experimental object spread operator.

Input source:

```
const variable = {
  ...user,
  avatar: 'http://www.example.com/something'
};
```

Output source:

```
const variable = {
  ...     user,
  avatar: 'http://www.example.com/something'
};
```

Expected?

```
const variable = {
  ...user,
  avatar: 'http://www.example.com/something'
};
```

**Comment by manuelstofer** [comment]
Yes! Would be great if it would format it like this:

``` javascript
const variable = {
  ...user,
  avatar: 'http://www.example.com/something'
};
```

**Comment by manuelstofer** [comment]
Closing, will merge https://github.com/manuelstofer/esformatter-align/pull/7 when its ready
