### ISSUE TITLE
Add config option for colon alignment in object declaration

### ISSUE THREAD

**Issue by Aaron-Pool** [manuelstofer/esformatter-align#6]
You have output looking like this:

```
{
  fieldName1:          value
  fieldNameOther:      value
  fieldName2:          value
  fieldNameOther2:     value
}
```

But I much prefer this:

```
{
  fieldName1           : value
  fieldNameOther       : value
  fieldName2           : value
  fieldNameOther2      : value
}
```

Because I think the vertical line created by the colon creates a greater visual distinction between
arrays and values.

Could this be a configurable option, please?

**Comment by manuelstofer** [comment]
Hi Aaron. Sure! Pull request is welcome.

**Comment by Aaron-Pool** [comment]
K! I'll see if I can get to it. I'm a big fan of esformatter. It's not QUITE there for what I want, and packages like https://atom.io/packages/aligner are currently my go to. But I would like to contribute to getting esformatter and it's plugins to a place where my formatting workflow is automatic, so I'll definitely try to PR this at some point.
